name: generate ascii artwork
on: push
jobs:
    first_job:
     runs-on: ubuntu-latest
     steps: 
     - name: checkout repo
       uses: actions/checkout@v6

     - name: list
       run: ls -lrta

     - name: Executing a script
       run: |
         chmod +x ascii.sh
         ./ascii.sh

     - name: list
       run: ls -lrta
