name: second workflow action
on: push
jobs:
    first_job:
     runs-on: ubuntu-latest
     steps: 
     - name: checkout repo
       uses: actions/checkout@v6

     - name: list files
       run: |
        echo "my first program"
        ls -rlta
        cat README.md
     - name: generate a Ascii artwork
       run: cowsay -f dragon “Run for cover, I am DRAGON” >> dragon.txt
